#!/bin/sh
# ganeti instances start init script
#
# chkconfig: 2345 99 01
# description: Ganeti Cluster Manager
### BEGIN INIT INFO
# Provides:          ganeti-watcher
# Required-Start:    $syslog $remote_fs ganeti
# Required-Stop:     $syslog $remote_fs ganeti
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Ganeti instances start script
# Description:       Ganeti instances start script
### END INIT INFO

## source vars from config
. /etc/default/ganeti

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
DESC="Ganeti cluster instances starting"

SCRIPTNAME="/etc/init.d/ganeti-start-inst"

if [ -r /lib/lsb/init-functions ]; then
  . /lib/lsb/init-functions
elif [ -r /etc/rc.d/init.d/functions ]; then
  . /etc/rc.d/init.d/functions
else
  echo "Unable to find init functions"
  exit 1
fi

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "$2"
        start-stop-daemon --start --exec "/usr/sbin/ganeti-watcher-startup" -b > /dev/null
	log_end_msg "0"
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" "$2"
        rm -f "$WATCHER_ACTIVE_FLAG"
	log_end_msg "0"
        ;;
    status)
        if [ -f "$WATCHER_ACTIVE_FLAG" ]; then
            echo "Ganeti watcher active"
        else
            echo "Ganeti watcher is not active"
        fi
        ;;
    *)
        log_success_msg "Usage: $SCRIPTNAME {start|stop|status}"
        exit 1
        ;;
esac

exit 0

